[package]
name = "bevy_lookup_curve"
keywords = ["bevy"]
license = "MIT OR Apache-2.0"
description = "Editable lookup curve for Bevy"
homepage = "https://crates.io/crates/bevy_lookup_curve"
documentation = "https://docs.rs/bevy_lookup_curve"
repository = "https://github.com/villor/bevy_lookup_curve"
readme = "README.md"
version = "0.2.0"
edition = "2021"

[dependencies]
# core
bevy_app = "0.13"
bevy_math = "0.13"
bevy_ecs = "0.13"
bevy_reflect = { version = "0.13", features = ['bevy'] }
bevy_log = "0.13"

# asset
bevy_asset = "0.13"
bevy_utils = "0.13"
ron = "0.8"
thiserror = "1.0"
serde = "1.0"

# egui editor
egui = "0.26"
bevy_egui = "0.25"

# egui inspector
# bevy_app = "0.10"
# bevy-inspector-egui = { version = "0.18", default-features = false }

[dev-dependencies]
bevy = { version = "0.13.0", default-features = false, features = ["x11", "bevy_winit", "bevy_sprite", "bevy_core_pipeline", "bevy_render", "bevy_asset", "png", "multi-threaded"] }
bevy-inspector-egui = { version = "0.23.1", default-features = false }
criterion = "0.5.1"
rand = "0.8.5"

# [[bench]]
# name = "lookup_curve"
# path = "benches/lookup_curve.rs"
# harness = false

[[bench]]
name = "knot_search"
path = "benches/knot_search.rs"
harness = false
