[package]
name = "bevy_lookup_curve"
keywords = ["bevy"]
license = "MIT OR Apache-2.0"
description = "Editable spline for animation and other stuff"
homepage = "https://crates.io/crates/bevy_lookup_curve"
documentation = "https://docs.rs/bevy_lookup_curve"
repository = "https://github.com/villor/bevy_lookup_curve"
readme = "README.md"
version = "0.1.0"
edition = "2021"

[dependencies]
# core
bevy_app = "0.12"
bevy_math = "0.12"
bevy_ecs = "0.12"
bevy_reflect = { version = "0.12", features = ['bevy'] }
bevy_log = "0.12"

# asset
bevy_asset = "0.12"
bevy_utils = "0.12"
ron = "0.8"
thiserror = "1.0"
serde = "1.0"

# egui editor
egui = "0.24"
bevy_egui = "0.24"

# egui inspector
# bevy_app = "0.10"
# bevy-inspector-egui = { version = "0.18", default-features = false }

[dev-dependencies]
bevy = { version = "0.12.1", default-features = false, features = ["x11", "bevy_winit", "bevy_sprite", "bevy_core_pipeline", "bevy_render", "bevy_asset", "png", "multi-threaded"] }
bevy-inspector-egui = { version = "0.22.1", default-features = false }
